blog/urls.py
from django.urls import path, re_path
from blog.views import *

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<slug:slug>/', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(), name="post_month_archive"),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name="post_day_archive"),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    #re_path(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),
    path('search/', SearchFormView.as_view(), name='search'),
    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='delete'),
]

mysite_base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from mysite_base.views import UserCreateView, UserCreateDoneTV

from mysite_base.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('bookmark/', include(('bookmark.urls', 'bookmark'), namespace='bookmark')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('books/', include(('books.urls', 'books'), namespace='books')),
    path('photo/', include(('photo.urls', 'photo'), namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from tagging.fields import TagField
from django.contrib.auth.models import User
from django.utils.text import slugify


# Create your models here.
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    tag = TagField()
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

blog/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic import ArchiveIndexView
from django.views.generic import YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

from blog.models import Post
from tagging.views import TaggedObjectList

from django.views.generic.edit import FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from mysite_base.views import LoginRequiredMixin


# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


class PostDV(DetailView):
    model = Post


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'archive/post_archive_today.html'


class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'


class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        schWord = "{0}".format(self.request.POST['search_word'])
        post_list = Post.objects.filter(Q(title__icontains=schWord) |
                                        Q(description__icontains=schWord) |
                                        Q(content__icontains=schWord)).distinct()

        context = dict()
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    initial = {'slug': 'auto-filling-do-not-input'}
    #fields = ['title', 'description', 'content', 'tag']
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tag']
    success_url = reverse_lazy('blog:index')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}
<div id="content">

<h1>Blog List</h1>

{% for post in posts %}
    <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

<br/>

<div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
        {% endif %}
    </span>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives until {% now "N d, Y" %}</h1>

<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a>
        </li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {%  for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {%  endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_today.html
{% extends "base.html" %}

{% block title %}post_archive_today.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<div id="content">

<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a>
        </li>
    {% endfor %}
</ul>
<br/>

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
        {% endfor %}
    </ul>
</div>

</div>
{% endblock %}

blog/templates/blog/post_change_list.html
{% extends "base.html" %}

{% block title %}post_change_list.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Change - {{ user }}</h1>

        <table class="change-list">
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>

            {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'blog:update' item.slug %}">Update</a></td>
                    <td><a href="{% url 'blog:delete' item.slug %}">Delete</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Delete</h1>

        <form action="." method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_detail.html{% endblock %}

{% block content %}
<div id="content">

<h1>{{ object.title }}</h1>

<p class="'other_posts">
    {% if object.get_previous_by_modify_date %}
        <a href="{{ object.get_previous_post.get_absolute_url }}" title="'View previous post">&laquo;--{{ object.get_previous_post }}</a>
    {% endif %}

    {% if object.get_next_by_modify_date %}
        | <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{ object.get_next_post }}--&raquo;</a>
    {% endif %}

</p>

<p class="date">{{ object.modify_date|date:"j F Y" }}</p>
<br/>

<div class="body">
    {{ object.content|linebreaks }}
</div>

<div>
    <b>TAGS: </b>
    {% load tagging_tags %}
    {% tags_for_object object as tags %}
    {% for tag in tags %}
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}</a>
    {% endfor %}
        <a href="{% url 'blog:tag_cloud' %}"><em>{TagCloud}</em></a>
</div>

<br>

<div>
    {% load disqus_tags %}
    {% disqus_show_comments %}
</div>

</div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}post_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Create/Update - {{ user }}</h1>

        <form action="." method="post">
            {% csrf_token %}
            {% if form.errors %}
                <p class="errornote">Wrong! Please correct the error(s) below.</p>
            {% endif %}

            <p>This is a creation or update form for your post.</p>
            <fieldset class="aligned">
                <div class="form-row">
                    {{ form.title.label_tag }} {{ form.title }}
                </div>
                <div class="form-row">
                    {{ form.slug.label_tag }} {{ form.slug }}
                </div>
                <div class="form-row">
                    {{ form.description.label_tag }} {{ form.description }}
                </div>
                <div class="form-row">
                    {{ form.content.label_tag }} {{ form.content }}
                </div>
                <div class="form-row">
                    {{ form.tag.label_tag }} {{ form.tag }}
                </div>
            </fieldset>

            <div class="submit-row">
                <input type="submit" value="Submit"/>
            </div>

            <script type="text/javascript">document.getElementById('id_title').focus();</script>
        </form>
    </div>
{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}
    <div id="content">
        <h1>Blog Search</h1>

        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <input type="submit" value="Submit"/>
        </form>

        <br/><br/>

        {% if object_list %}
            {% for post in object_list %}
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                {{ post.modify_date|date:"N, d, Y" }}
            {% endfor %}
        {% elif search_term %}
            <b><em>Search Word({{ search_term }}) Not Found</em></b>
        {% endif %}
    </div>
{% endblock content %}