blog/urls.py
from django.urls import path, re_path
from blog.views import *

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<slug:slug>/', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(), name="post_month_archive"),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name="post_day_archive"),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    #re_path(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),
    path('search/', SearchFormView.as_view(), name='search'),
    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='delete'),
]

mysite_base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from mysite_base.views import UserCreateView, UserCreateDoneTV

from mysite_base.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('bookmark/', include(('bookmark.urls', 'bookmark'), namespace='bookmark')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('books/', include(('books.urls', 'books'), namespace='books')),
    path('photo/', include(('photo.urls', 'photo'), namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', AlbumLV.as_view(), name='index'),
    path('album/', AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),
    path('album/add/', AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', AlbumDeleteView.as_view(), name='album_delete'),
    path('photo/add/', PhotoCreateView.as_view(), name='photo_add'),
    path('photo/change/', PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='photo_delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <meta http-equiv="cache-control" content="no-cache" />

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

    <div id="header">
        <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
        {% if user.is_active %}
            <h4 class="welcome">Welcome,
                <strong>{% firstof user.get_short_name user.get_username %}</strong>
                <a href="{% url 'password_change' %}">Change password</a>
                <a href="{% url 'logout' %}">Logout</a>
            </h4>
        {% else %}
            <h4 class="welcome">Welcome, Anonymous
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'register' %}">Register</a>
            </h4>
        {% endif %}
    </div>

    <div id="menu">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'polls:index' %}">Polls</a></li>
        <li><a href="{% url 'books:index' %}">Books</a></li>
        <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
        <li><a href="{% url 'blog:index' %}">Blog</a></li>
        <li><a href="{% url 'photo:index' %}">Photo</a></li>

        <li><a href="#">Add&bigtriangledown;</a>
            <ul>
                <li><a href="#">Polls</a></li>
                <li><a href="#">Books</a></li>
                <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
                <li><a href="{% url 'blog:add' %}">Blog</a></li>
                <li><a href="{% url 'photo:album_add' %}">Album</a></li>
                <li><a href="{% url 'photo:photo_add' %}">Photo</a></li>
            </ul>
        </li>
        <li><a href="#">Change&bigtriangledown;</a>
            <ul>
                <li><a href="#">Polls</a></li>
                <li><a href="#">Books</a></li>
                <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
                <li><a href="{% url 'blog:change' %}">Blog</a></li>
                <li><a href="{% url 'photo:album_change' %}">Album</a></li>
                <li><a href="{% url 'photo:photo_change' %}">Photo</a></li>
            </ul>
        </li>

        <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
        <li><a href="{% url 'blog:search' %}">Search</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
    </div>

    {% block content %}{% endblock %}

    {% block footer %}{% endblock %}

</body>

</html>

templates/home.html
{%  extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}
    <div id="content_home">
        <div id="homeimg">
            <a href="/"><img src="{% static 'img/gate.jpg' %}" style="height:256px;" /></a>
            <h4 style="margin: 0;">Karl's Homepage</h4>
        </div>

        <hr style="margin: 5px 0;">

        <h2>Select Application</h2>

        <table id=applist">
            <tr>
            <td><b><i><a href="{% url 'polls:index' %}">Polls</a></i></b></td>
            <td>polls</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
            </tr>

            <tr>
            <td><b><i><a href="{% url 'books:index' %}">Books</a></i></b></td>
            <td>Books</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
            </tr>

            <tr>
            <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
            <td>You can store your own bookmarks by Bookmark application.It's also possible to update or delete your bookmarks.</td>
            <td class="Edit"><i><a href="{% url 'bookmark:add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'bookmark:change' %}">Change</a></i></td>
            </tr>

            <tr>
            <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
            <td>This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc.</td>
            <td class="Edit"><i><a href="{% url 'blog:add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'blog:change' %}">Change</a></i></td>
            </tr>

            <tr>
            <td><b><i><a href="{% url 'photo:index' %}">Photo</a></i></b></td>
            <td>You can upload your own photos through this application. If you delete an album, all photos within it will be dleted.</td>
            <td class="Edit"><i><a href="{% url 'photo:album_add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'photo:album_change' %}">Change</a></i></td>
            </tr>
        </table>
    </div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; Karl 2018
</div>
{% endblock footer %}