blog/urls.py
from django.urls import path, re_path
from blog.views import *

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<slug:slug>/', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(), name="post_month_archive"),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name="post_day_archive"),
    path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('tag/', TagTV.as_view(), name='tag_cloud'),
    #re_path(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    path('tag/<str:tag>/', PostTOL.as_view(), name='tagged_object_list'),
    path('search/', SearchFormView.as_view(), name='search'),
    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeLV.as_view(), name='change'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='delete'),
]

books/urls.py
from django.urls import path
from books import views


urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),

    path('books/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

mysite_base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from mysite_base.views import UserCreateView, UserCreateDoneTV

from mysite_base.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('bookmark/', include(('bookmark.urls', 'bookmark'), namespace='bookmark')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('books/', include(('books.urls', 'books'), namespace='books')),
    path('photo/', include(('photo.urls', 'photo'), namespace='photo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title


class Author(models.Model):
    salutation = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

books/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView
from .models import Book, Author, Publisher


# Create your views here.
class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super(BooksModelView, self).get_context_data(**kwargs)
        context['object_list'] = ['Book', 'Author', 'Publisher']
        return context


class BookList(ListView):
    model = Book


class AuthorList(ListView):
    model = Author


class PublisherList(ListView):
    model = Publisher


class BookDetail(DetailView):
    model = Book


class AuthorDetail(DetailView):
    model = Author


class PublisherDetail(DetailView):
    model = Publisher

books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
    {{ block.super }}

    <div id="author_detail">
    {% block sidebar %}{{ block.super }}{% endblock sidebar %}
    <h1>{{ object.name }}</h1>
    <p>{{ object.salutation }}</p>
    <li>Email: {{ object.email }}</li>
    </div>
{% endblock content %}

books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    {{ block.super }}
    <div id="author_list">
    {% block sidebar %}{{ block.super }}{% endblock sidebar %}
    <h2>Authors List</h2>
    <ul>
        {% for author in object_list %}
            <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
        {% endfor %}
    </ul>
    </div>
{% endblock content %}

books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
    {{ block.super }}
    <div id="book_detail">
        {% block sidebar %}{{ block.super }}{% endblock sidebar %}
        <h1>{{ object.title }}</h1>
        <br>
        <li> Author:
            {% for author in object.authors.all %}
                {{ author }}
                {% if not forloop.last %},{% else %}{% endif %}
            {% endfor %}
        </li>
        <li>Publisher: {{ object.publisher }}</li>
        <li>Publication date: {{ object.publication_date }}</li>
    </div>
{% endblock content %}

books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}

    {{ block.super }}

    <div id="book_list">
    {% block sidebar %}{{ block.super }}{% endblock sidebar %}

    <h2>Books List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
    </div>
{% endblock content %}

books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}

    {{ block.super }}

    <div id="index">
    {% block sidebar %}{{ block.super }}{% endblock sidebar %}

    <h2>Books Management System</h2>
    <ul>
        {% for modelname in object_list %}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
                <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
            {% endwith %}
        {% endfor %}
    </ul>
    </div>
{% endblock content %}

books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
    {{ block.super }}
    <div id="publisher_detail">
        {% block sidebar %}{{ block.super }}{% endblock sidebar %}
        <h1>{{ object.name }}</h1>
        <p>{{ object.website }}</p>
        <li>Address: {{ object.address }}</li>
    </div>
{% endblock content %}

books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    {{ block.super }}
    <div id="publisher_list">
        {% block sidebar %}{{ block.super }}{% endblock sidebar %}
        <h2>Publisher List</h2>
        <ul>
            {% for publisher in object_list %}
                <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}